# Generated by Django 4.1.7 on 2023-03-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('price', models.DecimalField(decimal_places=6, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='photos/products')),
                ('view', models.IntegerField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
