# Generated by Django 4.1.7 on 2023-03-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name_plural': 'ordersDetail'},
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='ordersDetail',
        ),
    ]
